version: '2'
services:
  memcached:
    image: memcached:alpine
    ports:
      - "11212:11211"
    container_name: memcached

  data:
    image: busybox
    volumes:
      - ./misc/data:/var/lib/mysql
      - ./misc/phpmyadmin/sessions:/sessions
      - ../public:/var/www/html
    container_name: data

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "13306:3306"
    volumes_from:
      - data
    volumes:
      - ../application/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    container_name: mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./misc/phpmyadmin/sessions:/sessions
    container_name: phpmyadmin

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - data
    links:
      - web
    container_name: nginx

  web:
    build: ./php-fpm73   # <- if you want to use PHP7.3
    #    build: ./php-fpm72   # <- if you want to use PHP7.2
    #    build: ./php-fpm71
    #    build: ./php-fpm56    # <- if you want to use PHP5.6
    volumes_from:
      - data
    links:
      - mysql
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    container_name: web

  composer:
    build: ./composer
    volumes_from:
      - data
    links:
      - mysql
    container_name: composer
